### ISSUE TITLE
Can't install dependencies with Poetry

### ISSUE THREAD

**Issue by atosborges00** [nikvaessen/w2v2-speaker#12]
Hi, I'm having some trouble installing the dependencies with Poetry. I always get this error when Poetry is installing fairseq:

  ```
• Installing fairseq (0.10.2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "<string>", line 214, in <module>
    File "<string>", line 136, in do_setup
    File "/tmp/tmpdc61oe7j/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
      _install_setup_requires(attrs)
    File "/tmp/tmpdc61oe7j/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
      _fetch_build_eggs(dist)
    File "/tmp/tmpdc61oe7j/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
      dist.fetch_build_eggs(dist.setup_requires)
    File "/tmp/tmpdc61oe7j/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 74, in fetch_build_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/jovyan/.local/share/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/jovyan/.local/share/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/jovyan/.local/share/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/tmpdc61oe7j/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/tmpdc61oe7j/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/tmpdc61oe7j/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 217, in <module>
  IsADirectoryError: [Errno 21] Is a directory: 'fairseq/examples'
  

  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with fairseq (0.10.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "fairseq (==0.10.2)"'.
```

I also tried the suggestion at the end but it gives another Error:

```
Collecting fairseq==0.10.2
  Using cached fairseq-0.10.2.tar.gz (938 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "<string>", line 214, in <module>
        File "<string>", line 136, in do_setup
        File "/tmp/pip-build-env-067bbnv_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/tmp/pip-build-env-067bbnv_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/tmp/pip-build-env-067bbnv_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/tmp/pip-build-env-067bbnv_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 74, in fetch_build_eggs
          raise SetupRequirementsError(specifier_list)
      setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/jovyan/.cache/pypoetry/virtualenvs/wav2vec-speaker-identification-bn1jopCZ-py3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jovyan/.cache/pypoetry/virtualenvs/wav2vec-speaker-identification-bn1jopCZ-py3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jovyan/.cache/pypoetry/virtualenvs/wav2vec-speaker-identification-bn1jopCZ-py3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-067bbnv_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-067bbnv_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-067bbnv_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 217, in <module>
      IsADirectoryError: [Errno 21] Is a directory: 'fairseq/examples'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I also tried to update fairseq to v0.12.0 but the other dependencies in the project are not compatible. Do you have any suggestions or can you update the dependencies?

Edit: Forgot to mention: I'm using Ubuntu 20.04.5 LTS (Focal Fossa), python 3.9, pip 23.0.1

**Comment by nikvaessen** [comment]
You should probably be fine by just installing the list of dependencies with pip

**Comment by atosborges00** [comment]
Actually, I think it's a problem with the fairseq version. Apparently, v0.10.2 is a [problematic version](https://github.com/facebookresearch/fairseq/issues/3535). I was able to install v0.10.0. I hope it's enough to run.
